### PR TITLE
Model Test

### LINKED ISSUE #195: Adding duplicate task and team throws exception instead of error message
image
A task with the same task name can be added as long as the deadlines are not the same -- this is ok if we plan to allow such behaviour

image
But adding a task with the same task name, assignee and deadline throws an error instead of displaying an error message. Similar behavior for adding a team with the same team name as an existing team (try: "add team default" to reproduce).

### PR DESCRIPTION
**Pull request by changjy44**
### Changes
1. Add tests for all classes under models.
2. Fixed a bug where Duplicate Person will show when adding a task.
3. Changed all index to `index`

Fixes #195

### CODE REVIEW

File: src/test/java/seedu/address/model/TruthTableTest.java [hunk 1]
```diff
@@ -77,12 +81,63 @@ public void hasPerson_personWithSameIdentityFieldsInTruthTable_returnsTrue() {
...
     }
 
+
+    @Test
+    public void getTeamList_modifyList_throwsUnsupportedOperationException() {
+        assertThrows(UnsupportedOperationException.class, () -> truthTable.getTeamList().remove(0));
+    }
+
+
+
```
Comment (marcuspang) [inline src/test/java/seedu/address/model/TruthTableTest.java:140]:
```suggestion
    @Test
    public void getTeamList_modifyList_throwsUnsupportedOperationException() {
        assertThrows(UnsupportedOperationException.class, () -> truthTable.getTeamList().remove(0));
    }
```

File: src/test/java/seedu/address/testutil/LinkBuilder.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+    /**
+     * Sets the {@code Name} of the {@code Link} that we are building.
+     */
+    public LinkBuilder withName(String name) {
+        this.name = new LinkName(name);
+        return this;
+    }
+
+
```
Comment (marcuspang) [inline src/test/java/seedu/address/testutil/LinkBuilder.java:40]:
```suggestion
```

File: src/test/java/seedu/address/logic/parser/TruthTableParserTest.java [hunk 3]
```diff
@@ -1,182 +1,439 @@
...
+        UnmarkCommand command = (UnmarkCommand) parser.parseCommand(
+                UnmarkCommand.FULL_COMMAND + " " + INDEX_ONE.getOneBased());
+        assertEquals(INDEX_ONE, ParserHelper.getIndex(command));
     }
 
 
     @Test
     public void parseCommand_unrecognisedInput_throwsParseException() {
+
     }
```
Comment (marcuspang) [inline src/test/java/seedu/address/logic/parser/TruthTableParserTest.java:432]: To add implementation

**Review by marcuspang — APPROVED** [review]

File: src/test/java/seedu/address/logic/parser/TruthTableParserTest.java (hunk 3 above)
Comment (marcuspang) [reply src/test/java/seedu/address/logic/parser/TruthTableParserTest.java:432]: This would include
- empty spaces 
- non alphabet characters like numbers
