### PR TITLE
Fix add team, add task and edit team commands

### LINKED ISSUE #209: `add team default` does not show error message

### PR DESCRIPTION
**Pull request by changjy44**
### Changes
1. Fixed a bug where `add team default` will not show an error message
2. Fixed a bug where adding the exact same task details will not show an error message
3. Fixed a bug where editing team to an existing team name will not show an error message

Fixes #209

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditTeamCommand.java [hunk 1]
```diff
@@ -94,7 +95,10 @@ public CommandResult execute(Model model) throws CommandException {
         List<Team> teamList = model.getTeamList();
         List<Team> teamListCopy = new ArrayList<>(teamList);
 
-        if ((!editedTeam.isSameTeam(currentTeam)) && (teamListCopy.contains(editedTeam))) {
+        List<Team> filteredListWithTargetTeam = teamList.stream()
+                .filter(editedTeam::isSameTeam).collect(Collectors.toList());
+
+        if ((!editedTeam.isSameTeam(currentTeam)) && (filteredListWithTargetTeam.size() == 1)) {
```
Comment (marcuspang) [inline src/main/java/seedu/address/logic/commands/EditTeamCommand.java:101]:
```suggestion
        if (!editedTeam.isSameTeam(currentTeam) && filteredListWithTargetTeam.size() == 1) {
```

**Review by marcuspang — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/EditTeamCommand.java (hunk 1 above)
Comment (mjgui) [reply src/main/java/seedu/address/logic/commands/EditTeamCommand.java:101]: updated to say != 0 just in case lols
