### PR TITLE
Fix link commands to use link list of the correct team

### LINKED ISSUE #169: [PE-D][Tester D] Edit link command gives invalid link index error message for valid link index
As seen in the screenshot, edit link 1 -n "link" and edit link 2 -n "link" both give the error message "The link index provided is invalid" even though there are 2 links.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: pewggls/ped#11

### LINKED ISSUE #170: [PE-D][Tester D] Delete link command gives wrong error message
Expected the command "delete link 1" to delete the first link, but received the error message "The person index provided is invalid" instead.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: pewggls/ped#12

### PR DESCRIPTION
**Pull request by mjgui**
Closes #169 
Closes #170

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditLinkCommand.java [hunk 1]
```diff
@@ -81,7 +80,7 @@ public CommandResult execute(Model model) throws CommandException {
             return new CommandResult(commandSpec.commandLine().getUsageMessage());
         }
         requireNonNull(model);
-        List<Link> lastShownList = model.getFilteredLinkList();
+        List<Link> lastShownList = model.getLinkList();
 
         if (index.getZeroBased() >= lastShownList.size()) {
```
Comment (ling-ui) [inline src/main/java/seedu/address/logic/commands/EditLinkCommand.java:85]:
```suggestion
        if (index.getOneBased() > lastShownList.size()) {
```
