### PR TITLE
Fix ListTasksCommand `-i` and `-c` flags

### LINKED ISSUE #127: `list tasks -i` throws null pointer exception

### LINKED ISSUE #150: [PE-D][Tester A] List tasks in team: list tasks not working
Problem: Example shown in UG, `list tasks -i` not working as expected. Unable to enter the command, no error message shown, functionality expected not shown.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LianGuoYang/ped#12

### LINKED ISSUE #167: [PE-D][Tester D] list tasks -i does not do anything
According to the user guide, the command list tasks -i should list all the incomplete tasks of the current team, but instead nothing happened. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: pewggls/ped#9

### PR DESCRIPTION
**Pull request by mjgui**
Updated implementation to now update filtered list (i.e. list should change when you type `list tasks -i` or `-c`)

Bugfix: Previously it caused a Null Pointer Error due to use of boxed `Boolean` which could be `null` rather than simply `false`

Fixes #167 
Fixes #150 
Fixes #127

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ListTasksCommand.java [hunk 1]
```diff
@@ -4,61 +4,79 @@
...
 
-    @CommandLine.Option(names = {FLAG_COMPLETE_TASKS_STR, FLAG_COMPLETE_TASKS_STR_LONG},
+
+    @CommandLine.Option(names = { FLAG_COMPLETE_TASKS_STR, FLAG_COMPLETE_TASKS_STR_LONG },
             description = FLAG_COMPLETE_TASK_DESCRIPTION)
-    private Boolean isComplete;
+    private boolean hasCompleteFlag;
 
-    @CommandLine.Option(names = {FLAG_INCOMPLETE_TASKS_STR, FLAG_INCOMPLETE_TASKS_STR_LONG}, description =
+    @CommandLine.Option(names = { FLAG_INCOMPLETE_TASKS_STR, FLAG_INCOMPLETE_TASKS_STR_LONG }, description =
```
Comment (marcuspang) [inline src/main/java/seedu/address/logic/commands/ListTasksCommand.java:46]: Is your IntelliJ adding these spaces?

File: src/main/java/seedu/address/logic/commands/ListTasksCommand.java [hunk 2]
```diff
@@ -4,61 +4,79 @@
...
 import seedu.address.logic.commands.exceptions.CommandException;
 import seedu.address.model.Model;
+import seedu.address.model.team.Task;
 
 
 /**
  * Lists all tasks of the current team.
  */
-@CommandLine.Command(name = "tasks", aliases = {"t"}, mixinStandardHelpOptions = true)
+@CommandLine.Command(name = "tasks", aliases = { "t" }, mixinStandardHelpOptions = true)
```
Comment (marcuspang) [inline src/main/java/seedu/address/logic/commands/ListTasksCommand.java:25]: Same here for spaces

**Review by marcuspang — APPROVED** [review]
LGTM, not sure why where are spaces added to some flags, so please undo the change

**Review by ling-ui — APPROVED** [review]
